// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD-bzzD4ORpQxO9Mv-nHlXjFsHLetsMvI',
    appId: '1:616602685564:web:67c9eec9b056b2cc12b9f9',
    messagingSenderId: '616602685564',
    projectId: 'arminnovators-e1fb9',
    authDomain: 'arminnovators-e1fb9.firebaseapp.com',
    storageBucket: 'arminnovators-e1fb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoZ8dfEcXknHfS5qtY1lBM0k4VgrhyYGs',
    appId: '1:616602685564:android:71df3184151d2ef712b9f9',
    messagingSenderId: '616602685564',
    projectId: 'arminnovators-e1fb9',
    storageBucket: 'arminnovators-e1fb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBy7HjsWS1KVOtXXEmQ8sG8a-R8Chbg7A',
    appId: '1:616602685564:ios:39fd34b3cd67578212b9f9',
    messagingSenderId: '616602685564',
    projectId: 'arminnovators-e1fb9',
    storageBucket: 'arminnovators-e1fb9.appspot.com',
    iosBundleId: 'com.example.busTrackingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBy7HjsWS1KVOtXXEmQ8sG8a-R8Chbg7A',
    appId: '1:616602685564:ios:39fd34b3cd67578212b9f9',
    messagingSenderId: '616602685564',
    projectId: 'arminnovators-e1fb9',
    storageBucket: 'arminnovators-e1fb9.appspot.com',
    iosBundleId: 'com.example.busTrackingSystem',
  );
}
