// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYmG3uqFUtfmfS5RWCf359BGdwTOSQsiM',
    appId: '1:711637243935:web:bbf0a6eb967f3ce0699d2a',
    messagingSenderId: '711637243935',
    projectId: 'reddit-d',
    authDomain: 'reddit-d.firebaseapp.com',
    storageBucket: 'reddit-d.appspot.com',
    measurementId: 'G-RYX1YY6NY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1LcN8M8cshGpZUntAjKRryegmNAhyScg',
    appId: '1:711637243935:android:237d3d619bf47b09699d2a',
    messagingSenderId: '711637243935',
    projectId: 'reddit-d',
    storageBucket: 'reddit-d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa1FKjdLAqGf5ObDWd2DVWjrnAWHge1eA',
    appId: '1:711637243935:ios:c3d3a5ab4bdd647f699d2a',
    messagingSenderId: '711637243935',
    projectId: 'reddit-d',
    storageBucket: 'reddit-d.appspot.com',
    iosClientId: '711637243935-imv0fml5hoak2thdggdj8qqm2qm9g6hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.busTrackingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa1FKjdLAqGf5ObDWd2DVWjrnAWHge1eA',
    appId: '1:711637243935:ios:c3d3a5ab4bdd647f699d2a',
    messagingSenderId: '711637243935',
    projectId: 'reddit-d',
    storageBucket: 'reddit-d.appspot.com',
    iosClientId: '711637243935-imv0fml5hoak2thdggdj8qqm2qm9g6hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.busTrackingSystem',
  );
}
